/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/api-generator/': RouteRecordInfo<'/api-generator/', '/api-generator', Record<never, never>, Record<never, never>>,
    '/encrypt-dencrypt/': RouteRecordInfo<'/encrypt-dencrypt/', '/encrypt-dencrypt', Record<never, never>, Record<never, never>>,
    '/husky-test/': RouteRecordInfo<'/husky-test/', '/husky-test', Record<never, never>, Record<never, never>>,
    '/mock-generator/': RouteRecordInfo<'/mock-generator/', '/mock-generator', Record<never, never>, Record<never, never>>,
    '/permission-configure/': RouteRecordInfo<'/permission-configure/', '/permission-configure', Record<never, never>, Record<never, never>>,
    '/schema-generator/': RouteRecordInfo<'/schema-generator/', '/schema-generator', Record<never, never>, Record<never, never>>,
  }
}
